-- return {
--   "nvim-treesitter/nvim-treesitter",
--   config = function()
--     local configs = require("nvim-treesitter.configs")
--
--     configs.setup {
--       auto_install = true,
--       highlight = {
--         enable = true,
--       },
--     }
--   end,
-- }
